apiVersion: v1
kind: Pod
metadata:
  name: front-app-pod
  labels:
    name: front-app-pod
    app: demo-rick-app
spec:
  containers:
    - name: front-app
      image: guane-test/rick
      imagePullPolicy: Never
      ports:
        - containerPort: 80
  restartPolicy: Never