apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    name: front-service
    app: demo-rick-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: front-app-pod
    app: demo-rick-app